package cn.com.epoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-08T14:55:14.245+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://epoint.com.cn/", name = "PingBiaoInterfaceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PingBiaoInterfaceHttpPost {

    @WebMethod(operationName = "GetLastCommitBJHistoryDetail")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getLastCommitBJHistoryDetail(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "GetDanWeiKBBiaoDuan")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getDanWeiKBBiaoDuan(
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid,
        @WebParam(partName = "StartTime", name = "StartTime", targetNamespace = "http://epoint.com.cn/")
        java.lang.String startTime,
        @WebParam(partName = "EndTime", name = "EndTime", targetNamespace = "http://epoint.com.cn/")
        java.lang.String endTime,
        @WebParam(partName = "MD5", name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );

    @WebMethod(operationName = "UpdateBJInfo")
    public void updateBJInfo(
        @WebParam(partName = "xml", name = "xml", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml
    );

    @WebMethod(operationName = "UploadTBDWInfo")
    @WebResult(name = "boolean", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public boolean uploadTBDWInfo(
        @WebParam(partName = "ProjectGuid", name = "ProjectGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String projectGuid,
        @WebParam(partName = "XiaQuCode", name = "XiaQuCode", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xiaQuCode,
        @WebParam(partName = "PWD", name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd,
        @WebParam(partName = "XML", name = "XML", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml
    );

    @WebMethod(operationName = "GetLastEditBJHistoryDetail")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getLastEditBJHistoryDetail(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "GetBJHistoryDetail")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getBJHistoryDetail(
        @WebParam(partName = "BJGuid", name = "BJGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String bjGuid
    );

    @WebMethod(operationName = "GetNJHWBiaoDuan")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getNJHWBiaoDuan(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetMeetStatus")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getMeetStatus(
        @WebParam(partName = "MeetID", name = "MeetID", targetNamespace = "http://epoint.com.cn/")
        java.lang.String meetID
    );

    @WebMethod(operationName = "GetDanWeiBiaoDuan")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getDanWeiBiaoDuan(
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid,
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "MD5", name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );

    @WebMethod(operationName = "UploadFile")
    public void uploadFile(
        @WebParam(partName = "BiaoDuanNo", name = "BiaoDuanNo", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanNo,
        @WebParam(partName = "PingWeiName", name = "PingWeiName", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pingWeiName
    );

    @WebMethod(operationName = "GenBiaoDuanInfo")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String genBiaoDuanInfo(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetPingBiaoIsEnd")
    @WebResult(name = "boolean", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public boolean getPingBiaoIsEnd(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetNJHWDanWei")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getNJHWDanWei(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "UpdateBJQianZhangInfo")
    public void updateBJQianZhangInfo(
        @WebParam(partName = "BJGuid", name = "BJGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String bjGuid,
        @WebParam(partName = "AttachConName", name = "AttachConName", targetNamespace = "http://epoint.com.cn/")
        java.lang.String attachConName,
        @WebParam(partName = "IsQianZhang", name = "IsQianZhang", targetNamespace = "http://epoint.com.cn/")
        java.lang.String isQianZhang
    );

    @WebMethod(operationName = "GetPingBiaoBiaoDuanInfo")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getPingBiaoBiaoDuanInfo(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetMeetList")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getMeetList();

    @WebMethod(operationName = "GetBJHistoryByBJGuid")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getBJHistoryByBJGuid(
        @WebParam(partName = "BJGuid", name = "BJGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String bjGuid
    );

    @WebMethod(operationName = "GetPBDanWeiInfo")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getPBDanWeiInfo(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "IsEnd")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String isEnd(
        @WebParam(partName = "MeetingID", name = "MeetingID", targetNamespace = "http://epoint.com.cn/")
        java.lang.String meetingID
    );

    @WebMethod(operationName = "GetKBJLInfo")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getKBJLInfo(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "UpLoadProjectInfo")
    @WebResult(name = "boolean", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public boolean upLoadProjectInfo(
        @WebParam(partName = "XiaQuCode", name = "XiaQuCode", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xiaQuCode,
        @WebParam(partName = "XML", name = "XML", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml,
        @WebParam(partName = "ProjectGuid", name = "ProjectGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String projectGuid,
        @WebParam(partName = "PWD", name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd
    );

    @WebMethod(operationName = "UpdateDecrInfo")
    @WebResult(name = "boolean", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public boolean updateDecrInfo(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid,
        @WebParam(partName = "strDecrTB", name = "strDecrTB", targetNamespace = "http://epoint.com.cn/")
        java.lang.String strDecrTB
    );

    @WebMethod(operationName = "GetBJHistory")
    @WebResult(name = "DataSet", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getBJHistory(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "DanWeiGuid", name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "GetRoomInfo")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getRoomInfo(
        @WebParam(partName = "StartTime", name = "StartTime", targetNamespace = "http://epoint.com.cn/")
        java.lang.String startTime,
        @WebParam(partName = "EndTime", name = "EndTime", targetNamespace = "http://epoint.com.cn/")
        java.lang.String endTime
    );

    @WebMethod(operationName = "UploadPW_LibInfo")
    @WebResult(name = "boolean", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public boolean uploadPWLibInfo(
        @WebParam(partName = "XiaQuCode", name = "XiaQuCode", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xiaQuCode,
        @WebParam(partName = "PWD", name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd,
        @WebParam(partName = "XML", name = "XML", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml,
        @WebParam(partName = "ProjectGuid", name = "ProjectGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String projectGuid
    );

    @WebMethod(operationName = "GetPBResultInfo")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getPBResultInfo(
        @WebParam(partName = "Info", name = "Info", targetNamespace = "http://epoint.com.cn/")
        java.lang.String info,
        @WebParam(partName = "PWD", name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd
    );

    @WebMethod(operationName = "GetPingWeiLSDZDF")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getPingWeiLSDZDF(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "MD5", name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );

    @WebMethod(operationName = "GetPingWeiLSDDetailDF")
    @WebResult(name = "string", targetNamespace = "http://epoint.com.cn/", partName = "Body")
    public java.lang.String getPingWeiLSDDetailDF(
        @WebParam(partName = "BiaoDuanGuid", name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(partName = "MD5", name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );
}
