package cn.com.epoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-08T14:55:14.347+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://epoint.com.cn/", name = "PingBiaoInterfaceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PingBiaoInterfaceSoap {

    @WebMethod(operationName = "GetLastCommitBJHistoryDetail", action = "http://epoint.com.cn/GetLastCommitBJHistoryDetail")
    @RequestWrapper(localName = "GetLastCommitBJHistoryDetail", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetLastCommitBJHistoryDetail")
    @ResponseWrapper(localName = "GetLastCommitBJHistoryDetailResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetLastCommitBJHistoryDetailResponse")
    @WebResult(name = "GetLastCommitBJHistoryDetailResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getLastCommitBJHistoryDetail(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "GetDanWeiKBBiaoDuan", action = "http://epoint.com.cn/GetDanWeiKBBiaoDuan")
    @RequestWrapper(localName = "GetDanWeiKBBiaoDuan", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetDanWeiKBBiaoDuan")
    @ResponseWrapper(localName = "GetDanWeiKBBiaoDuanResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetDanWeiKBBiaoDuanResponse")
    @WebResult(name = "GetDanWeiKBBiaoDuanResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getDanWeiKBBiaoDuan(
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid,
        @WebParam(name = "StartTime", targetNamespace = "http://epoint.com.cn/")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://epoint.com.cn/")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );

    @WebMethod(operationName = "UpdateBJInfo", action = "http://epoint.com.cn/UpdateBJInfo")
    @RequestWrapper(localName = "UpdateBJInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpdateBJInfo")
    @ResponseWrapper(localName = "UpdateBJInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpdateBJInfoResponse")
    public void updateBJInfo(
        @WebParam(name = "xml", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml
    );

    @WebMethod(operationName = "UploadTBDWInfo", action = "http://epoint.com.cn/UploadTBDWInfo")
    @RequestWrapper(localName = "UploadTBDWInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UploadTBDWInfo")
    @ResponseWrapper(localName = "UploadTBDWInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UploadTBDWInfoResponse")
    @WebResult(name = "UploadTBDWInfoResult", targetNamespace = "http://epoint.com.cn/")
    public boolean uploadTBDWInfo(
        @WebParam(name = "ProjectGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String projectGuid,
        @WebParam(name = "XiaQuCode", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xiaQuCode,
        @WebParam(name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd,
        @WebParam(name = "XML", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml
    );

    @WebMethod(operationName = "GetLastEditBJHistoryDetail", action = "http://epoint.com.cn/GetLastEditBJHistoryDetail")
    @RequestWrapper(localName = "GetLastEditBJHistoryDetail", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetLastEditBJHistoryDetail")
    @ResponseWrapper(localName = "GetLastEditBJHistoryDetailResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetLastEditBJHistoryDetailResponse")
    @WebResult(name = "GetLastEditBJHistoryDetailResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getLastEditBJHistoryDetail(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "GetBJHistoryDetail", action = "http://epoint.com.cn/GetBJHistoryDetail")
    @RequestWrapper(localName = "GetBJHistoryDetail", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJHistoryDetail")
    @ResponseWrapper(localName = "GetBJHistoryDetailResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJHistoryDetailResponse")
    @WebResult(name = "GetBJHistoryDetailResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getBJHistoryDetail(
        @WebParam(name = "BJGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String bjGuid
    );

    @WebMethod(operationName = "GetNJHWBiaoDuan", action = "http://epoint.com.cn/GetNJHWBiaoDuan")
    @RequestWrapper(localName = "GetNJHWBiaoDuan", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetNJHWBiaoDuan")
    @ResponseWrapper(localName = "GetNJHWBiaoDuanResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetNJHWBiaoDuanResponse")
    @WebResult(name = "GetNJHWBiaoDuanResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getNJHWBiaoDuan(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetMeetStatus", action = "http://epoint.com.cn/GetMeetStatus")
    @RequestWrapper(localName = "GetMeetStatus", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetMeetStatus")
    @ResponseWrapper(localName = "GetMeetStatusResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetMeetStatusResponse")
    @WebResult(name = "GetMeetStatusResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getMeetStatus(
        @WebParam(name = "MeetID", targetNamespace = "http://epoint.com.cn/")
        java.lang.String meetID
    );

    @WebMethod(operationName = "GetDanWeiBiaoDuan", action = "http://epoint.com.cn/GetDanWeiBiaoDuan")
    @RequestWrapper(localName = "GetDanWeiBiaoDuan", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetDanWeiBiaoDuan")
    @ResponseWrapper(localName = "GetDanWeiBiaoDuanResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetDanWeiBiaoDuanResponse")
    @WebResult(name = "GetDanWeiBiaoDuanResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getDanWeiBiaoDuan(
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid,
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );

    @WebMethod(operationName = "UploadFile", action = "http://epoint.com.cn/UploadFile")
    @RequestWrapper(localName = "UploadFile", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UploadFile")
    @ResponseWrapper(localName = "UploadFileResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UploadFileResponse")
    public void uploadFile(
        @WebParam(name = "BiaoDuanNo", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanNo,
        @WebParam(name = "PingWeiName", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pingWeiName
    );

    @WebMethod(operationName = "GenBiaoDuanInfo", action = "http://epoint.com.cn/GenBiaoDuanInfo")
    @RequestWrapper(localName = "GenBiaoDuanInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GenBiaoDuanInfo")
    @ResponseWrapper(localName = "GenBiaoDuanInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GenBiaoDuanInfoResponse")
    @WebResult(name = "GenBiaoDuanInfoResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String genBiaoDuanInfo(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetPingBiaoIsEnd", action = "http://epoint.com.cn/GetPingBiaoIsEnd")
    @RequestWrapper(localName = "GetPingBiaoIsEnd", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingBiaoIsEnd")
    @ResponseWrapper(localName = "GetPingBiaoIsEndResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingBiaoIsEndResponse")
    @WebResult(name = "GetPingBiaoIsEndResult", targetNamespace = "http://epoint.com.cn/")
    public boolean getPingBiaoIsEnd(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetNJHWDanWei", action = "http://epoint.com.cn/GetNJHWDanWei")
    @RequestWrapper(localName = "GetNJHWDanWei", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetNJHWDanWei")
    @ResponseWrapper(localName = "GetNJHWDanWeiResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetNJHWDanWeiResponse")
    @WebResult(name = "GetNJHWDanWeiResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getNJHWDanWei(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "UpdateBJQianZhangInfo", action = "http://epoint.com.cn/UpdateBJQianZhangInfo")
    @RequestWrapper(localName = "UpdateBJQianZhangInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpdateBJQianZhangInfo")
    @ResponseWrapper(localName = "UpdateBJQianZhangInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpdateBJQianZhangInfoResponse")
    public void updateBJQianZhangInfo(
        @WebParam(name = "BJGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String bjGuid,
        @WebParam(name = "AttachConName", targetNamespace = "http://epoint.com.cn/")
        java.lang.String attachConName,
        @WebParam(name = "IsQianZhang", targetNamespace = "http://epoint.com.cn/")
        java.lang.String isQianZhang
    );

    @WebMethod(operationName = "GetPingBiaoBiaoDuanInfo", action = "http://epoint.com.cn/GetPingBiaoBiaoDuanInfo")
    @RequestWrapper(localName = "GetPingBiaoBiaoDuanInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingBiaoBiaoDuanInfo")
    @ResponseWrapper(localName = "GetPingBiaoBiaoDuanInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingBiaoBiaoDuanInfoResponse")
    @WebResult(name = "GetPingBiaoBiaoDuanInfoResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getPingBiaoBiaoDuanInfo(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "GetMeetList", action = "http://epoint.com.cn/GetMeetList")
    @RequestWrapper(localName = "GetMeetList", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetMeetList")
    @ResponseWrapper(localName = "GetMeetListResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetMeetListResponse")
    @WebResult(name = "GetMeetListResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getMeetList();

    @WebMethod(operationName = "GetBJHistoryByBJGuid", action = "http://epoint.com.cn/GetBJHistoryByBJGuid")
    @RequestWrapper(localName = "GetBJHistoryByBJGuid", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJHistoryByBJGuid")
    @ResponseWrapper(localName = "GetBJHistoryByBJGuidResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJHistoryByBJGuidResponse")
    @WebResult(name = "GetBJHistoryByBJGuidResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getBJHistoryByBJGuid(
        @WebParam(name = "BJGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String bjGuid
    );

    @WebMethod(operationName = "GetPBDanWeiInfo", action = "http://epoint.com.cn/GetPBDanWeiInfo")
    @RequestWrapper(localName = "GetPBDanWeiInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPBDanWeiInfo")
    @ResponseWrapper(localName = "GetPBDanWeiInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPBDanWeiInfoResponse")
    @WebResult(name = "GetPBDanWeiInfoResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getPBDanWeiInfo(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "IsEnd", action = "http://epoint.com.cn/IsEnd")
    @RequestWrapper(localName = "IsEnd", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.IsEnd")
    @ResponseWrapper(localName = "IsEndResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.IsEndResponse")
    @WebResult(name = "IsEndResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String isEnd(
        @WebParam(name = "MeetingID", targetNamespace = "http://epoint.com.cn/")
        java.lang.String meetingID
    );

    @WebMethod(operationName = "GetKBJLInfo", action = "http://epoint.com.cn/GetKBJLInfo")
    @RequestWrapper(localName = "GetKBJLInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetKBJLInfo")
    @ResponseWrapper(localName = "GetKBJLInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetKBJLInfoResponse")
    @WebResult(name = "GetKBJLInfoResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getKBJLInfo(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid
    );

    @WebMethod(operationName = "UpLoadProjectInfo", action = "http://epoint.com.cn/UpLoadProjectInfo")
    @RequestWrapper(localName = "UpLoadProjectInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpLoadProjectInfo")
    @ResponseWrapper(localName = "UpLoadProjectInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpLoadProjectInfoResponse")
    @WebResult(name = "UpLoadProjectInfoResult", targetNamespace = "http://epoint.com.cn/")
    public boolean upLoadProjectInfo(
        @WebParam(name = "XiaQuCode", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xiaQuCode,
        @WebParam(name = "XML", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml,
        @WebParam(name = "ProjectGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String projectGuid,
        @WebParam(name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd
    );

    @WebMethod(operationName = "UpdateDecrInfo", action = "http://epoint.com.cn/UpdateDecrInfo")
    @RequestWrapper(localName = "UpdateDecrInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpdateDecrInfo")
    @ResponseWrapper(localName = "UpdateDecrInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UpdateDecrInfoResponse")
    @WebResult(name = "UpdateDecrInfoResult", targetNamespace = "http://epoint.com.cn/")
    public boolean updateDecrInfo(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid,
        @WebParam(name = "strDecrTB", targetNamespace = "http://epoint.com.cn/")
        java.lang.String strDecrTB
    );

    @WebMethod(operationName = "GetBJHistory", action = "http://epoint.com.cn/GetBJHistory")
    @RequestWrapper(localName = "GetBJHistory", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJHistory")
    @ResponseWrapper(localName = "GetBJHistoryResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJHistoryResponse")
    @WebResult(name = "GetBJHistoryResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getBJHistory(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "DanWeiGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String danWeiGuid
    );

    @WebMethod(operationName = "GetBJBiaoDuanList", action = "http://epoint.com.cn/GetBJBiaoDuanList")
    @RequestWrapper(localName = "GetBJBiaoDuanList", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJBiaoDuanList")
    @ResponseWrapper(localName = "GetBJBiaoDuanListResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetBJBiaoDuanListResponse")
    public void getBJBiaoDuanList(
        @WebParam(name = "TName", targetNamespace = "http://epoint.com.cn/")
        java.lang.String tName,
        @WebParam(name = "PageSize", targetNamespace = "http://epoint.com.cn/")
        int pageSize,
        @WebParam(name = "CurrentPageIndex", targetNamespace = "http://epoint.com.cn/")
        int currentPageIndex,
        @WebParam(name = "UniqueField", targetNamespace = "http://epoint.com.cn/")
        java.lang.String uniqueField,
        @WebParam(name = "Where", targetNamespace = "http://epoint.com.cn/")
        java.lang.String where,
        @WebParam(name = "OrderBy", targetNamespace = "http://epoint.com.cn/")
        java.lang.String orderBy,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetBJBiaoDuanListResult", targetNamespace = "http://epoint.com.cn/")
        javax.xml.ws.Holder<java.lang.String> getBJBiaoDuanListResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "TotalNum", targetNamespace = "http://epoint.com.cn/")
        javax.xml.ws.Holder<java.lang.Integer> totalNum
    );

    @WebMethod(operationName = "GetRoomInfo", action = "http://epoint.com.cn/GetRoomInfo")
    @RequestWrapper(localName = "GetRoomInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetRoomInfo")
    @ResponseWrapper(localName = "GetRoomInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetRoomInfoResponse")
    @WebResult(name = "GetRoomInfoResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getRoomInfo(
        @WebParam(name = "StartTime", targetNamespace = "http://epoint.com.cn/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://epoint.com.cn/")
        java.lang.String endTime
    );

    @WebMethod(operationName = "UploadPW_LibInfo", action = "http://epoint.com.cn/UploadPW_LibInfo")
    @RequestWrapper(localName = "UploadPW_LibInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UploadPWLibInfo")
    @ResponseWrapper(localName = "UploadPW_LibInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.UploadPWLibInfoResponse")
    @WebResult(name = "UploadPW_LibInfoResult", targetNamespace = "http://epoint.com.cn/")
    public boolean uploadPWLibInfo(
        @WebParam(name = "XiaQuCode", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xiaQuCode,
        @WebParam(name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd,
        @WebParam(name = "XML", targetNamespace = "http://epoint.com.cn/")
        java.lang.String xml,
        @WebParam(name = "ProjectGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String projectGuid
    );

    @WebMethod(operationName = "GetPBResultInfo", action = "http://epoint.com.cn/GetPBResultInfo")
    @RequestWrapper(localName = "GetPBResultInfo", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPBResultInfo")
    @ResponseWrapper(localName = "GetPBResultInfoResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPBResultInfoResponse")
    @WebResult(name = "GetPBResultInfoResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getPBResultInfo(
        @WebParam(name = "Info", targetNamespace = "http://epoint.com.cn/")
        java.lang.String info,
        @WebParam(name = "PWD", targetNamespace = "http://epoint.com.cn/")
        java.lang.String pwd
    );

    @WebMethod(operationName = "GetPingWeiLSDZDF", action = "http://epoint.com.cn/GetPingWeiLSDZDF")
    @RequestWrapper(localName = "GetPingWeiLSDZDF", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingWeiLSDZDF")
    @ResponseWrapper(localName = "GetPingWeiLSDZDFResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingWeiLSDZDFResponse")
    @WebResult(name = "GetPingWeiLSDZDFResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getPingWeiLSDZDF(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );

    @WebMethod(operationName = "GetPingWeiLSDDetailDF", action = "http://epoint.com.cn/GetPingWeiLSDDetailDF")
    @RequestWrapper(localName = "GetPingWeiLSDDetailDF", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingWeiLSDDetailDF")
    @ResponseWrapper(localName = "GetPingWeiLSDDetailDFResponse", targetNamespace = "http://epoint.com.cn/", className = "cn.com.epoint.GetPingWeiLSDDetailDFResponse")
    @WebResult(name = "GetPingWeiLSDDetailDFResult", targetNamespace = "http://epoint.com.cn/")
    public java.lang.String getPingWeiLSDDetailDF(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://epoint.com.cn/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "MD5", targetNamespace = "http://epoint.com.cn/")
        java.lang.String md5
    );
}
