package cn.com.epoint;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-08T14:55:14.366+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "PingBiaoInterface", 
                  wsdlLocation = "F://a.wsdl",
                  targetNamespace = "http://epoint.com.cn/") 
public class PingBiaoInterface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://epoint.com.cn/", "PingBiaoInterface");
    public final static QName PingBiaoInterfaceHttpPost = new QName("http://epoint.com.cn/", "PingBiaoInterfaceHttpPost");
    public final static QName PingBiaoInterfaceHttpGet = new QName("http://epoint.com.cn/", "PingBiaoInterfaceHttpGet");
    public final static QName PingBiaoInterfaceSoap = new QName("http://epoint.com.cn/", "PingBiaoInterfaceSoap");
    public final static QName PingBiaoInterfaceSoap12 = new QName("http://epoint.com.cn/", "PingBiaoInterfaceSoap12");
    static {
        URL url = PingBiaoInterface.class.getResource("F://a.wsdl");
        if (url == null) {
            url = PingBiaoInterface.class.getClassLoader().getResource("F://a.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(PingBiaoInterface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "F://a.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public PingBiaoInterface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PingBiaoInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingBiaoInterface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PingBiaoInterface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PingBiaoInterface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PingBiaoInterface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PingBiaoInterfaceHttpPost
     */
    @WebEndpoint(name = "PingBiaoInterfaceHttpPost")
    public PingBiaoInterfaceHttpPost getPingBiaoInterfaceHttpPost() {
        return super.getPort(PingBiaoInterfaceHttpPost, PingBiaoInterfaceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PingBiaoInterfaceHttpPost
     */
    @WebEndpoint(name = "PingBiaoInterfaceHttpPost")
    public PingBiaoInterfaceHttpPost getPingBiaoInterfaceHttpPost(WebServiceFeature... features) {
        return super.getPort(PingBiaoInterfaceHttpPost, PingBiaoInterfaceHttpPost.class, features);
    }


    /**
     *
     * @return
     *     returns PingBiaoInterfaceHttpGet
     */
    @WebEndpoint(name = "PingBiaoInterfaceHttpGet")
    public PingBiaoInterfaceHttpGet getPingBiaoInterfaceHttpGet() {
        return super.getPort(PingBiaoInterfaceHttpGet, PingBiaoInterfaceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PingBiaoInterfaceHttpGet
     */
    @WebEndpoint(name = "PingBiaoInterfaceHttpGet")
    public PingBiaoInterfaceHttpGet getPingBiaoInterfaceHttpGet(WebServiceFeature... features) {
        return super.getPort(PingBiaoInterfaceHttpGet, PingBiaoInterfaceHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns PingBiaoInterfaceSoap
     */
    @WebEndpoint(name = "PingBiaoInterfaceSoap")
    public PingBiaoInterfaceSoap getPingBiaoInterfaceSoap() {
        return super.getPort(PingBiaoInterfaceSoap, PingBiaoInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PingBiaoInterfaceSoap
     */
    @WebEndpoint(name = "PingBiaoInterfaceSoap")
    public PingBiaoInterfaceSoap getPingBiaoInterfaceSoap(WebServiceFeature... features) {
        return super.getPort(PingBiaoInterfaceSoap, PingBiaoInterfaceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns PingBiaoInterfaceSoap
     */
    @WebEndpoint(name = "PingBiaoInterfaceSoap12")
    public PingBiaoInterfaceSoap getPingBiaoInterfaceSoap12() {
        return super.getPort(PingBiaoInterfaceSoap12, PingBiaoInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PingBiaoInterfaceSoap
     */
    @WebEndpoint(name = "PingBiaoInterfaceSoap12")
    public PingBiaoInterfaceSoap getPingBiaoInterfaceSoap12(WebServiceFeature... features) {
        return super.getPort(PingBiaoInterfaceSoap12, PingBiaoInterfaceSoap.class, features);
    }

}
