package com.dqhaihang.epoint.pingbiao_common.hhwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-01-19T22:40:40.759+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "HaiHangWebServiceService", 
                  wsdlLocation = "http://xinkwang-tppingbiao.haihangyun.cn/TPPingBiao/services/HaiHangInterface?wsdl",
                  targetNamespace = "http://HHWebService.PingBiao_Common.epoint.dqhaihang.com/") 
public class HaiHangWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://HHWebService.PingBiao_Common.epoint.dqhaihang.com/", "HaiHangWebServiceService");
    public final static QName HaiHangWebServicePort = new QName("http://HHWebService.PingBiao_Common.epoint.dqhaihang.com/", "HaiHangWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://xinkwang-tppingbiao.haihangyun.cn/TPPingBiao/services/HaiHangInterface?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HaiHangWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://xinkwang-tppingbiao.haihangyun.cn/TPPingBiao/services/HaiHangInterface?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HaiHangWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HaiHangWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HaiHangWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HaiHangWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HaiHangWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HaiHangWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HaiHangWebService
     */
    @WebEndpoint(name = "HaiHangWebServicePort")
    public HaiHangWebService getHaiHangWebServicePort() {
        return super.getPort(HaiHangWebServicePort, HaiHangWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HaiHangWebService
     */
    @WebEndpoint(name = "HaiHangWebServicePort")
    public HaiHangWebService getHaiHangWebServicePort(WebServiceFeature... features) {
        return super.getPort(HaiHangWebServicePort, HaiHangWebService.class, features);
    }

}
