package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-03T12:03:58.511+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "OnlineHallSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OnlineHallSoap {

    /**
     * <b><i>获取今日开标项目个数</i></b><br>
     *                                 <font color='blue'>string</font> CreateDateAfter: 时间<br>
     */
    @WebMethod(operationName = "GetTodayKBCountKBDT", action = "http://tempuri.org/GetTodayKBCountKBDT")
    @RequestWrapper(localName = "GetTodayKBCountKBDT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTodayKBCountKBDT")
    @ResponseWrapper(localName = "GetTodayKBCountKBDTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTodayKBCountKBDTResponse")
    @WebResult(name = "GetTodayKBCountKBDTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getTodayKBCountKBDT(
        @WebParam(name = "CreateDateAfter", targetNamespace = "http://tempuri.org/")
        java.lang.String createDateAfter
    );

    /**
     * <b><i>招标代理、投标人登录</i></b><br>
     *                                 <font color='blue'>string</font> usertype: 用户类型<br>
     *                                 <font color='blue'>string</font> strDognum: 锁号(1：用户名登录，参数传空)<br>
     *                                 <font color='blue'>string</font> md5: 校验码(**strDognum ## MD5值)<br>
     */
    @WebMethod(operationName = "GetHuiYuanUserinfoKBDT", action = "http://tempuri.org/GetHuiYuanUserinfoKBDT")
    @RequestWrapper(localName = "GetHuiYuanUserinfoKBDT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHuiYuanUserinfoKBDT")
    @ResponseWrapper(localName = "GetHuiYuanUserinfoKBDTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHuiYuanUserinfoKBDTResponse")
    @WebResult(name = "GetHuiYuanUserinfoKBDTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getHuiYuanUserinfoKBDT(
        @WebParam(name = "usertype", targetNamespace = "http://tempuri.org/")
        java.lang.String usertype,
        @WebParam(name = "strDognum", targetNamespace = "http://tempuri.org/")
        java.lang.String strDognum,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        java.lang.String md5
    );

    /**
     * <b><i>获取单位今日所有开标项目</i></b><br>
     *                                 <font color='blue'>string</font> Danweiguid: 单位标识<br>
     *                                 <font color='blue'>string</font> Mima: 密码<br>
     */
    @WebMethod(operationName = "GetNJHWDanwei", action = "http://tempuri.org/GetNJHWDanwei")
    @RequestWrapper(localName = "GetNJHWDanwei", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNJHWDanwei")
    @ResponseWrapper(localName = "GetNJHWDanweiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNJHWDanweiResponse")
    @WebResult(name = "GetNJHWDanweiResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getNJHWDanwei(
        @WebParam(name = "Danweiguid", targetNamespace = "http://tempuri.org/")
        java.lang.String danweiguid,
        @WebParam(name = "Mima", targetNamespace = "http://tempuri.org/")
        java.lang.String mima
    );

    /**
     * <b><i>工作人员登录</i></b><br>
     *                                 <font color='blue'>string</font> loginID: 用户名<br>
     *                                 <font color='blue'>string</font> loginKey: 密码(CA登录密码传空)<br>
     *                                 <font color='blue'>string</font> strDognum: 锁号(1：用户名登录，参数传空)<br>
     *                                 <font color='blue'>string</font> logintype: 登录方式(1：用户名，密码登录,2：CA登录)<br>
     *                                 <font color='blue'>string</font> md5: 校验码(**loginID## MD5值)<br>
     */
    @WebMethod(operationName = "GetFrameUserinfoKBDT", action = "http://tempuri.org/GetFrameUserinfoKBDT")
    @RequestWrapper(localName = "GetFrameUserinfoKBDT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFrameUserinfoKBDT")
    @ResponseWrapper(localName = "GetFrameUserinfoKBDTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFrameUserinfoKBDTResponse")
    @WebResult(name = "GetFrameUserinfoKBDTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getFrameUserinfoKBDT(
        @WebParam(name = "loginID", targetNamespace = "http://tempuri.org/")
        java.lang.String loginID,
        @WebParam(name = "loginKey", targetNamespace = "http://tempuri.org/")
        java.lang.String loginKey,
        @WebParam(name = "strDognum", targetNamespace = "http://tempuri.org/")
        java.lang.String strDognum,
        @WebParam(name = "logintype", targetNamespace = "http://tempuri.org/")
        java.lang.String logintype,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        java.lang.String md5
    );

    /**
     * <b><i>获取标段信息</i></b><br>
     *                                 <font color='blue'>string</font> BiaoDuanGuid: 标段唯一标识<br>
     *                                 <font color='blue'>string</font> CreateDateAfter: 时间<br>
     *                                 <font color='blue'>string</font> md5: 校验码<br>
     *                                 <font color='blue'>string</font> DaiLiGuid: 代理GUID<br>
     */
    @WebMethod(operationName = "GetBiaoDuanKBDT", action = "http://tempuri.org/GetBiaoDuanKBDT")
    @RequestWrapper(localName = "GetBiaoDuanKBDT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBiaoDuanKBDT")
    @ResponseWrapper(localName = "GetBiaoDuanKBDTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBiaoDuanKBDTResponse")
    @WebResult(name = "GetBiaoDuanKBDTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getBiaoDuanKBDT(
        @WebParam(name = "BiaoDuanGuid", targetNamespace = "http://tempuri.org/")
        java.lang.String biaoDuanGuid,
        @WebParam(name = "CreateDateAfter", targetNamespace = "http://tempuri.org/")
        java.lang.String createDateAfter,
        @WebParam(name = "md5", targetNamespace = "http://tempuri.org/")
        java.lang.String md5,
        @WebParam(name = "DaiLiGuid", targetNamespace = "http://tempuri.org/")
        java.lang.String daiLiGuid
    );
}
