package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-03T12:03:58.605+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "OnlineHall", 
                  wsdlLocation = "http://hwjy.njzwfw.gov.cn:8080/TradingService/OnlineHall.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class OnlineHall extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OnlineHall");
    public final static QName OnlineHallSoap12 = new QName("http://tempuri.org/", "OnlineHallSoap12");
    public final static QName OnlineHallSoap = new QName("http://tempuri.org/", "OnlineHallSoap");
    public final static QName OnlineHallHttpGet = new QName("http://tempuri.org/", "OnlineHallHttpGet");
    public final static QName OnlineHallHttpPost = new QName("http://tempuri.org/", "OnlineHallHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("http://hwjy.njzwfw.gov.cn:8080/TradingService/OnlineHall.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnlineHall.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hwjy.njzwfw.gov.cn:8080/TradingService/OnlineHall.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public OnlineHall(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnlineHall(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlineHall() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OnlineHall(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OnlineHall(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OnlineHall(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OnlineHallSoap
     */
    @WebEndpoint(name = "OnlineHallSoap12")
    public OnlineHallSoap getOnlineHallSoap12() {
        return super.getPort(OnlineHallSoap12, OnlineHallSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineHallSoap
     */
    @WebEndpoint(name = "OnlineHallSoap12")
    public OnlineHallSoap getOnlineHallSoap12(WebServiceFeature... features) {
        return super.getPort(OnlineHallSoap12, OnlineHallSoap.class, features);
    }


    /**
     *
     * @return
     *     returns OnlineHallSoap
     */
    @WebEndpoint(name = "OnlineHallSoap")
    public OnlineHallSoap getOnlineHallSoap() {
        return super.getPort(OnlineHallSoap, OnlineHallSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineHallSoap
     */
    @WebEndpoint(name = "OnlineHallSoap")
    public OnlineHallSoap getOnlineHallSoap(WebServiceFeature... features) {
        return super.getPort(OnlineHallSoap, OnlineHallSoap.class, features);
    }


    /**
     *
     * @return
     *     returns OnlineHallHttpGet
     */
    @WebEndpoint(name = "OnlineHallHttpGet")
    public OnlineHallHttpGet getOnlineHallHttpGet() {
        return super.getPort(OnlineHallHttpGet, OnlineHallHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineHallHttpGet
     */
    @WebEndpoint(name = "OnlineHallHttpGet")
    public OnlineHallHttpGet getOnlineHallHttpGet(WebServiceFeature... features) {
        return super.getPort(OnlineHallHttpGet, OnlineHallHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns OnlineHallHttpPost
     */
    @WebEndpoint(name = "OnlineHallHttpPost")
    public OnlineHallHttpPost getOnlineHallHttpPost() {
        return super.getPort(OnlineHallHttpPost, OnlineHallHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineHallHttpPost
     */
    @WebEndpoint(name = "OnlineHallHttpPost")
    public OnlineHallHttpPost getOnlineHallHttpPost(WebServiceFeature... features) {
        return super.getPort(OnlineHallHttpPost, OnlineHallHttpPost.class, features);
    }

}
